name: hello_world
on: push
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Step 1
        run: echo "$(cat hello_world.txt)"
      - name: Step 2
        run: echo "$(cat hello_world1.txt)"
